name = "Gabe nunez"
current_city = "Tucson, AZ"
current_occupation = "Account Servicing Manager"
current_age = 40
years_married = 2
number_of_siblings = 5
pocket_change = 0.81
career_batting_average = .335
percentage_of_year_over = .5178
traveled_to_england = false
traveled_to_costa_rica = true
completed_data_types_lesson = true
